# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%cd /work/
%run /work/initialise.py

/work


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.26.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [15]:
Z = np.zeros(10)
print(Z.size * Z.itemsize)
print(Z.nbytes)

80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [26]:
arr = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
arr = np.flip(arr)
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [33]:
arr = np.array([1,2,2,0,4,0])
np.nonzero(arr)

(array([0, 1, 2, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [35]:
np.random.rand(3,3,3)

array([[[0.21488022, 0.19345943, 0.32582349],
        [0.75098381, 0.64568929, 0.63216535],
        [0.02318892, 0.9916481 , 0.57837308]],

       [[0.16186435, 0.58045146, 0.42860154],
        [0.77571387, 0.90354036, 0.10732048],
        [0.26430956, 0.71592353, 0.40298887]],

       [[0.40402448, 0.44023025, 0.10523357],
        [0.94534795, 0.67609278, 0.70645168],
        [0.89173354, 0.24009923, 0.59435861]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
arr = np.random.random((10,10))
print(f"max={arr.max()}, min={arr.min()}")

max=0.9892743915689552, min=0.02145002240995364


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [42]:
arr = np.random.random((30,))
arr.mean()

0.44861142879885946

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [44]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
np.pad(arr, 1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [54]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
0.3 == 3 * 0.1

nan
False
False
nan
True


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [56]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [59]:
arr = np.zeros((8,8))
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [65]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [66]:
np.tile([[1, 0], [0, 1]], [4,4])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [73]:
arr = np.random.random((5,5)) 
(arr - arr.mean()) / (arr.std())

array([[ 0.05208773, -0.60517815,  0.86069717,  0.83723245, -1.28324883],
       [ 1.79488398, -0.46266622,  0.86379621, -0.07119938,  1.31037528],
       [ 1.75405886, -1.06343396, -0.86713029, -1.03063493, -0.74629125],
       [-1.20461792,  0.34837752,  1.20823471, -0.5846614 , -1.10673385],
       [-0.97994121,  0.73061086, -0.37140534, -0.84023213,  1.45702008]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [87]:
color_t = np.dtype([('r', np.ubyte), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8),])
arr = np.empty((3), dtype=color_t)
np.array([(1,2,3,4), (5,6,7,8)], dtype=color_t)


array([(1, 2, 3, 4), (5, 6, 7, 8)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [91]:
A = np.random.random((5,3))
B = np.random.random((3,2))
A @ B

array([[0.73290587, 0.4724204 ],
       [1.17307506, 0.97521344],
       [0.93489306, 0.70196413],
       [0.85830033, 0.74566475],
       [1.05037029, 0.87564071]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [102]:
arr = np.arange(10)
arr[(3<=arr) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [3]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [17]:
Z = np.arange(10)
print(Z ** Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [22]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int))

nan
0
[-9223372036854775808]


/tmp/ipykernel_8841/1574041313.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_8841/1574041313.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_8841/1574041313.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int))


#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
Z = np.random.uniform(-10, +10, 10)
print(Z)
np.copysign(np.ceil(np.abs(Z)), Z)

[ 3.63680959  7.52429565  5.92129601  1.64579643 -6.51083938  2.83597917
 -0.04287597 -1.14173797 -6.97003452  6.18779652]


array([ 4.,  8.,  6.,  2., -7.,  3., -1., -2., -7.,  7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
Z1 = np.arange(0,10)
Z2 = np.arange(5,18)
np.intersect1d(Z1,Z2)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [47]:
np.seterr(all="ignore")
np.seterr(all="print")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [54]:
import datetime
today = np.datetime64("today", "D")
tomorrow = today + np.timedelta64(1, "D")
yesterday = today - np.timedelta64(1, "D")
print(today, tomorrow, yesterday)


2023-10-13 2023-10-14 2023-10-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [71]:
np.arange("2016-07", "2016-08", dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [75]:
A = np.arange(10, dtype=np.float64)
B = np.arange(10, dtype=np.float64)

np.add(A, B, out=B)
np.multiply(A, -0.5, out=A)
np.multiply(A, B, out=A)
A

array([ -0.,  -1.,  -4.,  -9., -16., -25., -36., -49., -64., -81.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [89]:
A = np.random.uniform(0, 100, (10))
print(np.floor(A))
print(A.astype(np.int32))
print(A - A % 1)
print(A // 1)
print(np.trunc(A))

[86. 98.  6. 81. 34. 93. 26. 76. 16. 32.]
[86 98  6 81 34 93 26 76 16 32]
[86. 98.  6. 81. 34. 93. 26. 76. 16. 32.]
[86. 98.  6. 81. 34. 93. 26. 76. 16. 32.]
[86. 98.  6. 81. 34. 93. 26. 76. 16. 32.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [100]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
print(np.tile([0, 1, 2, 3, 4], (5, 1)))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [106]:
def f():
    for i in range(10):
        yield i
gen = f()
np.fromiter(gen, dtype=np.int32, count=-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [112]:
np.linspace(0, 1, 11, endpoint=False)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [114]:
np.sort(np.random.rand(10))

array([0.04826679, 0.29845454, 0.43131365, 0.54658443, 0.56496619,
       0.66519027, 0.684992  , 0.73882589, 0.80758626, 0.89150244])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [116]:
arr = np.random.random((10,))
np.add.reduce(arr)

3.8901652139628253

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [120]:
A = np.random.random(10)
B = np.random.random(10)
np.allclose(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [127]:
arr = np.arange(10)
arr.flags.writeable = False
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [133]:
mat = np.random.random((10, 2))
(np.sqrt(mat[:, 0]**2 + mat[:, 1]**2), np.arctan2(mat[:, 1], mat[:, 0]))

(array([0.73469866, 0.51726547, 0.500441  , 0.89603406, 0.79172139,
        0.57330741, 0.32999493, 1.08214486, 0.89422235, 0.84485146]),
 array([0.93738005, 0.66919462, 0.91606845, 1.51288878, 0.9135362 ,
        0.86028574, 1.18862257, 0.53033613, 0.0073853 , 1.4981077 ]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [137]:
arr = np.random.random(10)
print(arr)
arr[np.argmax(arr)] = 0
print(arr)

[0.30908731 0.94601547 0.77528442 0.33811351 0.74154969 0.92992796
 0.9926715  0.99731992 0.83264386 0.7899711 ]
[0.30908731 0.94601547 0.77528442 0.33811351 0.74154969 0.92992796
 0.9926715  0.         0.83264386 0.7899711 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [144]:
arr = np.zeros((5,5), [('x', float), ('y', float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
arr


array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [154]:
X = np.linspace(1, 5, 5)
Y = np.linspace(-7, -3, 5)
1/np.subtract.outer(X, Y)

array([[0.125     , 0.14285714, 0.16666667, 0.2       , 0.25      ],
       [0.11111111, 0.125     , 0.14285714, 0.16666667, 0.2       ],
       [0.1       , 0.11111111, 0.125     , 0.14285714, 0.16666667],
       [0.09090909, 0.1       , 0.11111111, 0.125     , 0.14285714],
       [0.08333333, 0.09090909, 0.1       , 0.11111111, 0.125     ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [160]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [163]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [166]:
arr = np.linspace(1,10,10)
arr[((arr - 3) ** 2).argmin()]

3.0

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [171]:
answer(51)
np.zeros(10, [ ("position", [("x", np.float64), ("y", np.float64)]), ("color", [("r", np.int8), ("g", np.int8), ("b", np.int8)])])

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


array([((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', 'i1'), ('g', 'i1'), ('b', 'i1')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [189]:
arr = np.random.random((10,2))
X, Y = np.atleast_2d(arr[:, 0], arr[:, 1])
print(np.sqrt((X-X.T)**2 + (Y-Y.T)**2))

[[0.         0.59574874 0.31571312 0.28103757 0.27801751 0.50898944
  0.39076081 0.37978506 0.14073703 0.1204132 ]
 [0.59574874 0.         0.91120932 0.76766428 0.42917799 0.38723295
  0.2999846  0.82295576 0.73150188 0.47716321]
 [0.31571312 0.91120932 0.         0.29770081 0.56035471 0.77079465
  0.68411863 0.40068035 0.18252087 0.43428991]
 [0.28103757 0.76766428 0.29770081 0.         0.54984764 0.52582349
  0.48692888 0.59837168 0.20786084 0.33941287]
 [0.27801751 0.42917799 0.56035471 0.54984764 0.         0.54315726
  0.38437812 0.39379246 0.41023203 0.22173206]
 [0.50898944 0.38723295 0.77079465 0.52582349 0.54315726 0.
  0.1597776  0.86519649 0.59729991 0.41068115]
 [0.39076081 0.2999846  0.68411863 0.48692888 0.38437812 0.1597776
  0.         0.72273261 0.50263972 0.27811251]
 [0.37978506 0.82295576 0.40068035 0.59837168 0.39379246 0.86519649
  0.72273261 0.         0.39053302 0.45536338]
 [0.14073703 0.73150188 0.18252087 0.20786084 0.41023203 0.59729991
  0.50263972 0.390533

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [195]:
arr = (np.random.random(10) * 100).astype(np.float32)
arr[:] = arr.view(np.int32)
arr


array([1.0866668e+09, 1.1169911e+09, 1.1059963e+09, 1.0816326e+09,
       1.1164861e+09, 1.1036099e+09, 1.1169368e+09, 1.1118941e+09,
       1.1200259e+09, 1.1138853e+09], dtype=float32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [203]:
from io import StringIO
txt = StringIO("""
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")
np.genfromtxt(txt, delimiter=",", dtype=int)


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [206]:
for (i,  x) in np.ndenumerate(np.random.rand(1,2)):
    print(i,x)

(0, 0) 0.7243412243936189
(0, 1) 0.979560750010268
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [208]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [224]:
arr = np.tile(np.linspace(0,100,5), (5, 1))

np.put(arr, np.random.choice(range(5*5), 3, replace=False), 1)
arr

array([[  0.,  25.,  50.,   1., 100.],
       [  0.,  25.,  50.,  75., 100.],
       [  0.,  25.,  50.,  75.,   1.],
       [  0.,  25.,  50.,  75.,   1.],
       [  0.,  25.,  50.,  75., 100.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [235]:
mat = np.random.random((5,5))
print(mat)
mat - np.mean(mat, axis=1, keepdims=True)

[[0.22311937 0.97588325 0.43123811 0.21220675 0.02500552]
 [0.19877928 0.65742497 0.44696163 0.93728544 0.39705731]
 [0.70750298 0.89141913 0.99837463 0.89383949 0.75643734]
 [0.45667714 0.22954384 0.60137095 0.78040783 0.74539669]
 [0.44309226 0.30149189 0.92897924 0.98696021 0.87329546]]
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)